### ISSUE TITLE
FE6-1 Item Listing cards

### ISSUE THREAD

**Issue by aaadam3042** [AyushmaanTomar/ELEC5619_Group_07#14]
Create an item listing card in react and tsx.

<img width="64" alt="Screenshot 2023-08-28 at 11 13 41 am" src="https://github.com/AyushmaanTomar/ELEC5619_Group_07/assets/69839172/9862cf83-334e-4032-8f43-d0aa155229d7">

**Comment by AyushmaanTomar** [comment]
Done :))
