### ISSUE TITLE
FE6-2 Create item list component

### ISSUE THREAD

**Issue by aaadam3042** [AyushmaanTomar/ELEC5619_Group_07#15]
Create the component to list all cards.

<img width="207" alt="Screenshot 2023-08-28 at 11 17 52 am" src="https://github.com/AyushmaanTomar/ELEC5619_Group_07/assets/69839172/c6feb88f-cd3a-43c4-a02c-4928592319e3">

**Comment by AyushmaanTomar** [comment]
Done :))
